### ISSUE TITLE
Use :public_key.cacerts_get for OTP 25+

### ISSUE THREAD

**Issue by yordis** [launchdarkly/erlang-server-sdk#113]
**Is your feature request related to a problem? 

When calling `:ldclient_config.tls_basic_options()` is giving us the following warning:

```text
[warning] TLS options are falling back to using the certifi store.
    This means the OS certificate store was not in the default location (/etc/ssl/certs/ca-certificates.crt).
    Please specify a custom location. You can use tls_ca_certfile_options, or fully specify the tls_options.
    You may see this warning in development on Mac/Windows.
```

I understand the warning is expected in development for Mac/Wins, but the situation could be improve for OTP 25+

**Describe the solution you'd like**

Use `:public_key.cacerts_get()` for OTP 25+ when calling `:ldclient_config.tls_basic_options()` or even better, add sensitive SSL options by default here https://github.com/launchdarkly/erlang-server-sdk/blob/124544eb183c48ddb243ceafa667c2f362d7f2e0/src/ldclient_config.erl#L130

**Describe alternatives you've considered**

Maintain sensitive configuration in our end:

```elixir
[
      verify: :verify_peer,
      cacerts: :public_key.cacerts_get(),
      depth: 3,
      customize_hostname_check: [
        match_fun: :public_key.pkix_verify_hostname_match_fun(:https)
      ]
    ]
```

I do not consider a security expert myself so having a sensitive default that I do not mess around with is really valuable.

**Additional context**
Add any other context about the feature request here.

**Comment by yordis** [comment]
Feedback from the SRE team (and myself) is that they would rather control the certificates using the VM/Container than rely on libraries. They are a cadence for the Containers to be updated and whatnot.

**Comment by yordis** [comment]
Related to https://erlef.github.io/security-wg/secure_coding_and_deployment_hardening/ssl

Do you have any opinions about using the following config in OTP25+

```elixir
[
  verify: :verify_peer,
  cacerts: :public_key.cacerts_get(),
  depth: 3,
  customize_hostname_check: [
    match_fun: :public_key.pkix_verify_hostname_match_fun(:https)
  ]
]
```

Also, I gather some feedback from the Erlang Ecosystem Foundation:

> Bram Verburg:
> Setting ciphers used to be important in older OTP versions, especially in servers, as by default it enabled a lot of legacy/unsafe ciphers. In newer OTP versions the standard list is quite safe and it is often not necessary to override it

**Comment by kinyoklion** [comment]
That seems reasonable.

Personally I am most comfortable when I have verified that at least some bad cases do fail. Being as positive cases pass even without TLS.

For instance doing a couple httpc requests with your config to known bad endpoints. I would have recommended badssl.com, but unfortunately it seems to have become unmaintained as some of the "good" configurations now have expired certs.

**Comment by yordis** [comment]
@kinyoklion any thoughts about https://github.com/launchdarkly/erlang-server-sdk/pull/114
