### ISSUE TITLE
Broken links in the README

### ISSUE THREAD

**Issue by hez** [launchdarkly/erlang-server-sdk#2]
It looks like all the links to reference docs are broken here.  In the README it links to https://docs.launchdarkly.com/docs/erlang-sdk-reference but that gives me a 404.

**Comment by unix1** [comment]
Thank you for reporting. We are aware the documentation is lacking currently. This should be resolved for the beta release. Stay tuned.

**Comment by zurab-darkly** [comment]
The links now work because we added the guide with the 1.0.0-beta releases.

**Comment by hez** [comment]
Thank you for all the hard work! 🥂
