### ISSUE TITLE
api/events/bulk not used in relay-proxy

### ISSUE THREAD

**Issue by yingyingtang-brex** [launchdarkly/erlang-server-sdk#29]
currently we have `event_url` defined as:
`EventsUri = ldclient_settings:get_value(Tag, events_uri) ++ "/api/events/bulk",` [here](https://github.com/launchdarkly/erlang-server-sdk/blob/027b3f66b2bf5f0e4e863c66b6cf767bf3a9989f/src/ldclient_event_process_server.erl#L64).

However it seems LD relay-proxy handles path `/bulk` only [here](https://github.com/launchdarkly/ld-relay/blob/cbc6f60a1cb9909bf85a5a5158d88fa730a4c3a7/relay.go#L383). 

This results in error `Permanent error sending events ['HTTP/1.1', 32, 52, 48, 52, 32, 'Not Found'` when trying connecting erlang server-sdk to the relay-proxy.

Should we update `event_url` to work with relay-proxy? e.g. we could provide `event_url` to override the default path. 

**SDK version**
erlang-server-sdk

**Comment by torchhound** [comment]
Hi @yingyingtang-brex thanks for reporting this bug!

Filed internally as 89932.

**Comment by bwoskow-ld** [comment]
@yingyingtang-brex apologies for leaving this issue open for so long, but this bug was resolved in [version 1.0.0](https://github.com/launchdarkly/erlang-server-sdk/releases/tag/1.0.0) of this SDK.
