### ISSUE TITLE
Unable to pass atoms as custom attribute keys

### ISSUE THREAD

**Issue by JafferN** [launchdarkly/erlang-server-sdk#36]
**Describe the bug**
Using an atom in the `custom` map will never match any of the feature toggle's rule but will still show the custom attribute in the user's attributes on the dashboard.

**To reproduce**
Create a feature flag with a rule that only returns the `true` variation when `subscription` is `LEVEL1`. Using this map as your user 
```elixir
user = %{
  :key => "1",
  :email => "test@email.com",
  :custom => %{:subscription => "LEVEL1"}
}
```
will always return `{1, false, :fallthrough}` when called with `:ldclient.variation_detail("level-1-subscription", user, false)` but when you use 
```elixir
user = %{
  :key => "1",
  :email => "test@email.com",
  :custom => %{"subscription" => "LEVEL1"}
}
```
it will return `{0, true, {:rule_match, 0, ""}}`.

**Expected behavior**
Using an atom in the `custom` map should still match the rule.

**SDK version**
1.1.0

**Language version, developer tools**
Elixir 1.11.4-otp-23 & Phoenix 1.5.7

**OS/platform**
macOS Big Sur

**Comment by zurab-darkly** [comment]
Hi @JafferN, thank you for reporting the issue. If you're creating the raw user the [custom_attributes](https://github.com/launchdarkly/erlang-server-sdk/blob/6a586e83765d25b624bb9167fd68de419dd9e9df/src/ldclient_user.erl#L36) is defined as a map from `binary() := any()`. So we expect all custom attribute keys to be binary. Conversely, all built-in attribute names are atoms.

However, if you'd like to supply your own custom attribute keys that may be atoms, you can use `ldclient_user:set/3` which will convert the atom to binary and then behave as you expect, keeping in mind that if you specify one of the built-in attribute names, they'll be treated as such - for example, you couldn't have an atom `key` (Elixir `:key`) as a custom attribute name using this function.

Is this sufficient, or were you looking to see more convenience functions around this in the SDK?

**Comment by JafferN** [comment]
Thanks for the reply, @zurab-darkly! I'm using binary rather than atoms now but it was just more so that it was a bit confusing that it didn't seem consistent. When I had used atoms in the custom attributes it was still setting those attributes in the user's object which could be seen on LaunchDarkly's website but would then be evaluated incorrectly using `variation`.

**Comment by zurab-darkly** [comment]
Right, that does sound inconsistent. I've filed internally as issue 113891.
