### ISSUE TITLE
deps source causes confusion

### ISSUE THREAD

**Issue by hez** [launchdarkly/erlang-server-sdk#4]
Using github instead of hex for rebar deps causes issues with resolving versions, other libraries we use require jsx and shotgun but pull them from the hex.pm repository.

Is there any reason all the deps here are pulled from github?

https://github.com/launchdarkly/erlang-server-sdk/blob/master/rebar.config#L3

Secondly it looks like the head ver of shotgun is used, this is going to also cause issues with version resolution for other libraries that depend on it. Why head? Maybe we can get a new ver of shotgun cut, it looks like the last ver was in 2016 according to his github repo.

**Comment by unix1** [comment]
Hello @hez, thank you for reporting this. Package management related changes are part of the pending tasks blocking beta release. We also plan to publish it on hex.pm. In the meantime, if you already have some fixes you'd like to contribute, we'll gladly review and merge.

Also, you are right about shotgun. The master branch has some required fixes that are not in the last published tag.

**Comment by hez** [comment]
Looks like there was a new shotgun release cut! https://github.com/inaka/shotgun/releases/tag/0.4.0

**Comment by unix1** [comment]
Closing this, thank you!
