### ISSUE TITLE
Wrong context shuts down GenServer

### ISSUE THREAD

**Issue by Sgoettschkes** [launchdarkly/erlang-server-sdk#69]
**Disclaimer**
We are using the LaunchDarkly SDK in an Elixir project and with my limited knowledge of Erlang, I'll stick to Elixir code to be as precise as possible.

**Describe the bug**

The code

    :ldclient_context.new_multi_from([
      :ldclient_context.new_from_map(%{key: "my-key", kind: "user"}),
      :ldclient_context.new_from_map(%{})
      ])

results in the following map

    %{:kind => "multi", "user" => %{}}

Passing this to `:ldclient.variation/3` as the context did result in an exception that took down the GenServer:

`no function clause matching in :ldclient_context.canonical_part/3`

**To reproduce**

```
:ldclient.start_instance(SDK_KEY)

context = :ldclient_context.new_multi_from([
  :ldclient_context.new_from_map(%{key: "my-key", kind: "user"}),
  :ldclient_context.new_from_map(%{})
  ])

:ldclient.variation("my_flag", context, false)
```

**Expected behavior**
I think there are two issues here:

1. The second context seems to overwrite the first one although it's not a valid context.
2. An invalid context shuts down the GenServer

I am not sure what the expected behavior for both of those is. For the first one, maybe not overwriting a valid context? As for the second one, returning the default flag and raising the issue in the logs (like it is done if the feature flag name does not exist on LD?

**SDK version**
We are using 2.0.0

**Language version, developer tools**
erlang 25.2
elixir 1.14.2

**OS/platform**
Docker image public.ecr.aws/docker/library/ubuntu:focal-20211006

**Comment by kinyoklion** [comment]
@Sgoettschkes Thank you for the issue. I will look into it, as this clearly should not cause the gen server to have an exception. 

That said, this specific context will result in default values. All of the context components making a multi-context must be valid. If they are not, then the entire context is invalid. It likely isn't overwriting the context so much as we stop converting it when we realize it is invalid. Likely it would be better for it to more clearly provide an invalid result.

In the situation you are encountering are you attempting to make a multi-context, and one happened to be invalid?

**Comment by kinyoklion** [comment]
It looks like we are missing a context validity check on that path. So I will get that resolved.

If you are dynamically generating a context, and it contains multiple parts, and you want to be sure the generated context is valid, then you could check each part using the `ldclient_context:is_valid` before putting them into the multi-context. The context would still be invalid if it didn't contain at least one context.

**Comment by kinyoklion** [comment]
To explain the context shape you get, here are a few comments from the code docs:

new_from_map
```
%% No kind was included, so it was defaulted to a <<"user">> kind.
```

new_multi_from
```
%% Each of the contexts being combined should have unique keys. If more than one context of the same kind is added,
%% then only a single context of the duplicated type will remain.
```
So
```
:ldclient_context.new_multi_from([
  :ldclient_context.new_from_map(%{key: "my-key", kind: "user"}),
  :ldclient_context.new_from_map(%{})
  ])
```
Is equivalent to
```
:ldclient_context.new_multi_from([
  :ldclient_context.new_from_map(%{key: "my-key", kind: "user"}),
  :ldclient_context.new_from_map(%{kind: "user"})
  ])
```
Which means the second replaces the first.

**Comment by Sgoettschkes** [comment]
Thanks for returning so soon and for being so detailed, @kinyoklion!

> In the situation you are encountering are you attempting to make a multi-context, and one happened to be invalid?

Yes, the error was on our side because we have a user context and a company context, but in certain situations, the user does not belong to a company. Our approach was to pass in an empty map in this case, not realizing this would cause the issue described above. Our solution now is to check if the user belongs to a company first and either use one `context_from_map` for the user alone or a `new_multi_from` for the user and company.

I prefer the function throwing an error or returning an error tuple if any input was invalid. But if the GenServer validates and writes an error to the log and returns the default, I would also be ok.

**Comment by kinyoklion** [comment]
If you were to evaluate this context using the detail methods, then you will get an error in the reason. `{error, user_not_specified}`.  The fix is in for the crash and I should be releasing it soon. We try not to only produce exceptions for things that are likely coding errors and less so likely to just be logic issues.

**Comment by kinyoklion** [comment]
Version 2.0.1 has been released and it should resolve the gen server crash. Thank you!
