### ISSUE TITLE
Upgrade `gun` to `v2.0.0`

### ISSUE THREAD

**Issue by beligante** [launchdarkly/erlang-server-sdk#71]
**Is your feature request related to a problem? Please describe.**
Internally in our projects, we're using gun 2.0.0 (the official release), and we would like to know if you're open to doing the same. 

**Describe the solution you'd like**
currently on the [master branch of `shotgun`](https://github.com/inaka/shotgun) they're also supporting Gun 2.0.0 (even tho shotgun doesn't support H2). By looking at the LD project looks like it's also a straightforward change here https://github.com/launchdarkly/erlang-server-sdk/blob/main/src/ldclient_http_options.erl#L62

Replacing the transport_opts with the new naming:

```erlang
gun_parse_tls_options(#{tls_options := TlsOptions}, GunOptions) ->
    GunOptions#{
        transport_opts => TlsOptions
    }.
```

to

```erlang
gun_parse_tls_options(#{tls_options := TlsOptions}, GunOptions) ->
    GunOptions#{
        tls_opts => TlsOptions
    }.
```

**Comment by kinyoklion** [comment]
Hello @beligante,

Thank you for bringing that shotgun update to our attention. The incompatibility between various libraries depending on gun 1/2/and a google fork of 2, has been a rough spot for us for a bit. 

Thanks,
Ryan

_Filed internally as 157120_

**Comment by tclugao** [comment]
I meet the same issue! my project gun is 2.0.0, and can not integrate the erlang-server-sdk

**Comment by balins** [comment]
[`shotgun`](https://github.com/inaka/shotgun), that in version `0.5.3` required `gun` `1.3.1`, has been recently updated to `1.0.1` which now depends on `gun` `2.0.1`.
Does this get us closer for a release of the SDK with `gun` `2.0` support?

**Comment by kinyoklion** [comment]
@balins If you want to try gun 2 support you can try this branch: https://github.com/launchdarkly/erlang-server-sdk/tree/rlamb/upgrade-to-gun-2

Because this would break any customer that has an existing dependency on gun 1.x it will likely be a major release of the SDK.

I am not certain on the timing yet. 

Thank you,
Ryan

**Comment by kinyoklion** [comment]
@beligante, @balins and @castengo Support for gun 2.x has been release in 3.0.0.
